<?php
// PDF export for Item Trace — uses wkhtmltopdf if configured, otherwise Dompdf if available.
// Requires running inside FA environment (db_query, db_fetch) and wkhtmltopdf path configured in sanity_config['wkhtmltopdf_path'] if binary not on PATH.
require __DIR__ . '/../src/ItemTrace.php';

if (!function_exists('db_query')) {
    http_response_code(500);
    echo "This export must run inside FrontAccounting environment with DB helpers available.";
    exit;
}

// get params
$stock = isset($_GET['stock_id']) ? $_GET['stock_id'] : null;
$loc = isset($_GET['location_id']) ? $_GET['location_id'] : null;
if (!$stock || !$loc) { http_response_code(400); echo "Missing stock_id or location_id"; exit; }

$it = new FA\Sanity\ItemTrace();
$assignments = $it->fifoConsume($stock, $loc);

// render HTML with header/footer for PDF
$companyLogo = null;
$logoRes = db_query("SELECT config_value FROM sanity_config WHERE config_key='company_logo_url' LIMIT 1");
if ($logoRow = db_fetch($logoRes)) { $companyLogo = trim(json_decode($logoRow['config_value'], true)); }

$html = '<!doctype html><html><head><meta charset="utf-8"><title>Trace '.htmlspecialchars($stock).'</title>';
$html .= '<style>body{font-family:Arial,Helvetica,sans-serif;margin:20px}header{display:flex;align-items:center;margin-bottom:12px}header img{max-height:60px;margin-right:12px}h1{font-size:18px;margin:0}footer{font-size:11px;color:#666;margin-top:18px;border-top:1px solid #ddd;padding-top:6px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:6px;text-align:left}</style></head><body>';
$html .= '<header>';
if ($companyLogo) { $html .= '<img src="'.htmlspecialchars($companyLogo).'" alt="logo"/>'; }
$html .= '<div><h1>Item Trace: '.htmlspecialchars($stock).' @ '.htmlspecialchars($loc).'</h1><div>Generated: '.date('Y-m-d H:i').'</div></div></header>';
$html .= '<table><thead><tr><th>Inbound</th><th>In Date</th><th>Qty</th><th>Assigned Qty</th><th>Outbound</th><th>Out Date</th></tr></thead><tbody>';
foreach ($assignments as $a) {
    $html .= '<tr>';
    $html .= '<td>'.htmlspecialchars($a['in_doc_no']??'').'</td>';
    $html .= '<td>'.htmlspecialchars($a['in_date']??'').'</td>';
    $html .= '<td>'.htmlspecialchars($a['in_qty']??'').'</td>';
    $html .= '<td>'.htmlspecialchars($a['assigned_qty']??'').'</td>';
    $html .= '<td>'.htmlspecialchars($a['out_doc_no']??'').'</td>';
    $html .= '<td>'.htmlspecialchars($a['out_date']??'').'</td>';
    $html .= '</tr>';
}
$html .= '</tbody></table>';
$html .= '<footer>Report generated by FA Sanity Check module. Review anomalies in the FA web UI.</footer></body></html>';

$basePath = sys_get_temp_dir();
// Try wkhtmltopdf first
$wk = null;
$res = db_query("SELECT config_value FROM sanity_config WHERE config_key='wkhtmltopdf_path' LIMIT 1");
if ($r = db_fetch($res)) { $wk = trim(json_decode($r['config_value'], true)); }
if (!$wk) $wk = 'wkhtmltopdf';

$tmpHtml = tempnam(sys_get_temp_dir(), 'trace_') . '.html';
$tmpPdf = tempnam(sys_get_temp_dir(), 'trace_') . '.pdf';
file_put_contents($tmpHtml, $html);

// build wkhtmltopdf options: header/footer and margins
$companyName = null;
$cRes = db_query("SELECT config_value FROM sanity_config WHERE config_key='company_name' LIMIT 1");
if ($cRow = db_fetch($cRes)) { $companyName = trim(json_decode($cRow['config_value'], true)); }
$headerLeft = $companyName ? $companyName : '';
$footerRight = 'Page [page] of [toPage]';
$opts = " --margin-top 15mm --margin-bottom 20mm --header-left " . escapeshellarg($headerLeft) . " --footer-right " . escapeshellarg($footerRight) . " ";
$cmd = escapeshellcmd($wk) . $opts . ' ' . escapeshellarg($tmpHtml) . ' ' . escapeshellarg($tmpPdf);
$execOk = false;
@exec($cmd, $out, $exit);
if ($exit === 0 && file_exists($tmpPdf)) {
    $execOk = true;
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="item_trace_'.preg_replace('/[^A-Za-z0-9_-]/','', $stock).'.pdf"');
    readfile($tmpPdf);
    @unlink($tmpHtml); @unlink($tmpPdf);
    exit;
}

// Fallback to Dompdf if available — include page numbers via Dompdf script
if (class_exists('\Dompdf\Dompdf')) {
    // Insert page-number script for Dompdf
    if (strpos($html, '<script type="text/php">') === false) {
        $pageScript = "<script type=\"text/php\">\nif (isset(\$pdf)) {\n  \$font = \$fontMetrics->get_font('Helvetica', 'normal');\n  \$pdf->page_text(520, 820, 'Page {PAGE_NUM} of {PAGE_COUNT}', \$font, 10, array(0,0,0));\n}\n</script>";
        $html = str_replace('</body></html>', $pageScript . '</body></html>', $html);
    }
    $dom = new \Dompdf\Dompdf();
    $dom->loadHtml($html);
    $dom->setPaper('A4', 'landscape');
    $dom->render();
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="item_trace_'.preg_replace('/[^A-Za-z0-9_-]/','', $stock).'.pdf"');
    echo $dom->output();
    @unlink($tmpHtml);
    exit;
}

// If we reach here, no PDF path
@unlink($tmpHtml);
http_response_code(500);
echo "No PDF renderer available. Install wkhtmltopdf and configure 'wkhtmltopdf_path' in sanity_config, or install Dompdf via Composer.";
